import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import './globals.css'
import { Inter } from 'next/font/google'
import BootstrapClient from '@/components/BootstrapClient.js';
import Navbar from "../components/Navbar";
import Footer from '@/components/Footer';


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'CA Anik Gupta',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <div className="pb-5"> {/* Add padding-top and padding-bottom here */}
        {children}
      </div>
        <BootstrapClient />
        <Footer/>
      </body>
    </html>
  )
}